#!/bin/bash

avgfile () {
	if [ ! -d $1 ]; then
		echo "The $1 directory does not exist"
	else
        sum_file_size=0;
        sum_count_file=0;
		for file in $(ls $1); do
            test -f $1/$file
			if [[ $? -eq '0' ]] ; then
				file_size=$(stat -c "%s" $1/$file)
                ((sum_count_file+=1))
				((sum_file_size+=file_size))
			fi
		done
		echo $(($sum_file_size/$sum_count_file))
	
	fi;
}
avgfile /home/parrot/Downloads/task/
