#!/bin/bash
while true 
do
sleep 5
uptime_avg=$(uptime | awk '{print $1 $8 $9 $10}')
free_1=$(free -b | sed -n '2p' | awk '{print $3}')
free_2=$(free -b | sed -n '2p' | awk '{print $2}')
df_1=$(df / | sed -n '2p' | awk '{print $4}')
df_2=$(df / | sed -n '2p' | awk '{print $2}')
echo "$uptime_avg $free_1 $free_2 $df_1 $df_2">>syslog.log

done
