#!/bin/bash
echo "Choose a mathematical operation to calculate:"
select operation in A+B A-B A/B A*B; do
    case $operation in
    A+B)
        echo "You have chosen A+B"
    echo "Choose the first number (A)"
    read a
    if [[ $a =~ [^a-zA-Z] ]]&&[[ $a != *+* ]]&&[[ $a != *-* ]]&&[[ $a != */* ]]&&[[ $a != *\** ]]; then
        echo "A=$a"
        echo "Choose the second number (B)"
        read b
        if [[ $b =~ [^a-zA-Z] ]]&&[[ $a != *+* ]]&&[[ $a != *-* ]]&&[[ $a != */* ]]&&[[ $a != *\** ]]; then
            echo "B=$b"
            echo "$a+$b=$(awk -v a=$a -v b=$b 'BEGIN{printf("%.3f\n", a+b)}')"
            exit
        else
            echo "Choose a NUMBER!"
            exit
        fi
    else
        echo "Choose a NUMBER!"
        exit
    fi
    ;;
    A-B)
        echo "You have chosen A-B"
    echo "Choose the first number (A)"
    read a
    if [[ $a =~ [^a-zA-Z] ]]&&[[ $a != *+* ]]&&[[ $a != *-* ]]&&[[ $a != */* ]]&&[[ $a != *\** ]]; then
        echo "A=$a"
        echo "Choose the second number (B)"
        read b
        if [[ $b =~ [^a-zA-Z] ]]&&[[ $a != *+* ]]&&[[ $a != *-* ]]&&[[ $a != */* ]]&&[[ $a != *\** ]]; then
            echo "B=$b"
            echo "$a-$b=$(awk -v a=$a -v b=$b 'BEGIN{printf("%.3f\n", a-b)}')"
            exit
        else
            echo "Choose a NUMBER!"
            exit
        fi
    else
        echo "Choose a NUMBER!"
        exit
    fi
    ;;
    A/B)
        echo "You have chosen A/B"
    echo "Choose the first number (A)"
    read a
    if [[ $a =~ [^a-zA-Z] ]]&&[[ $a != *+* ]]&&[[ $a != *-* ]]&&[[ $a != */* ]]&&[[ $a != *\** ]]; then
        echo "A=$a"
        echo "Choose the second number (B)"
        read b
        if [[ $b =~ [^a-zA-Z] ]]&&[[ $b -ne 0 ]]&&[[ $a != *+* ]]&&[[ $a != *-* ]]&&[[ $a != */* ]]&&[[ $a != *\** ]]; then
            echo "B=$b"
            echo "$a/$b=$(awk -v a=$a -v b=$b 'BEGIN{printf("%.3f\n", a/b)}')"
            exit
        else
            echo "Choose a NUMBER and not 0!"
            exit
        fi
    else
        echo "Choose a NUMBER!"
        exit
    fi
    ;;
    A*B)
        echo "You have chosen A*B"
    echo "Choose the first number (A)"
    read a
    if [[ $a =~ [^a-zA-Z] ]]&&[[ $a != *+* ]]&&[[ $a != *-* ]]&&[[ $a != */* ]]&&[[ $a != *\** ]]; then
        echo "A=$a"
        echo "Choose the second number (B)"
        read b
        if [[ $b =~ [^a-zA-Z] ]]&&[[ $a != *+* ]]&&[[ $a != *-* ]]&&[[ $a != */* ]]&&[[ $a != *\** ]]; then
            echo "B=$b"
            echo "$a*$b=$(awk -v a=$a -v b=$b 'BEGIN{printf("%.3f\n", a*b)}')"
            exit
        else
            echo "Choose a NUMBER!"
            exit
        fi
    else
        echo "Choose a NUMBER!"
        exit
    fi
    ;;
    esac
done

